### ISSUE TITLE
Moving hk2-osgi-resource-locator to hk2-extras breaks building, circular dependencies

### ISSUE THREAD

**Issue by wltjr** [javaee/hk2#369]
Commit ef8e4989ec39edcfa3d1b9416c02be0c265dc2fd that moved hk2-osgi-resource-locator to hk2-extras breaks building, at least it does for me on Gentoo.

hk2-api depends on hk2-osgi-resource-locator. hk2-extras needs hk2-api. osgi-resource-locator likely needs to reside on its own again. Not sure how others are not running into this. I am unable to build beta 44 as a result of this. Stuck at hk2-utils, as anything beyond that has circular dependencies not resolved due to the move.

Please consider reverting this change to allow pieces to build on their own as it did up till beta 43. Thank you!

**Comment by wltjr** [comment]
Not sure how this builds for others, ServiceLoader no longer seems to exist in hk2 repo. The [pom.xml](https://github.com/javaee/hk2/blob/master/hk2-api/pom.xml#L89) still references the missing package
```
hk2-2.5.0-b44/hk2-api/src/main/java/org/glassfish/hk2/internal/ServiceLocatorFactoryImpl.java:54: error: package org.glassfish.hk2.osgiresourcelocator does not exist
import org.glassfish.hk2.osgiresourcelocator.ServiceLoader;
                                            ^
src/main/java/org/glassfish/hk2/internal/ServiceLocatorFactoryImpl.java:113: error: cannot find symbol
          return ServiceLoader.lookupProviderInstances(ServiceLocatorGenerator.class);
                 ^
  symbol:   variable ServiceLoader
  location: class ServiceLocatorFactoryImpl
```

**Comment by wltjr** [comment]
@jwells131313 Can you look into this since you did the move? The breakage is not showing due the pom.xml pulling in the <artifactId>osgi-resource-locator</artifactId>. Which binds current versions of hk2 to previous ones as it needs that from older to build current.

**Comment by glassfishrobot** [comment]
**Closing this as this issue is migrated to** https://github.com/eclipse-ee4j/glassfish-hk2/issues/370
